version: '3'

services:
  jekyll:
    container_name: eofWebDevEnv
    ports:
      - '4000:4000'
      - '35729:35729'
    entrypoint:
      - jekyll
      - serve
      - -H
      - '0.0.0.0'
      - --livereload
      - --livereload-port
      - '35729'
      - --force_polling
      - --incremental
      # - --verbose
      # - --trace